-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\conv_core_ip_pkg.vhd
-- Created: 2025-04-19 00:07:41
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE conv_core_ip_pkg IS
  TYPE vector_of_real IS ARRAY (NATURAL RANGE <>) OF real;
END conv_core_ip_pkg;

