-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\sobelFilter2024a\conv_core_ip_src_color_correct_core.vhd
-- Created: 2025-04-19 00:07:28
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: conv_core_ip_src_color_correct_core
-- Source Path: sobelFilter2024a/conv_core/color_correct_core
-- Hierarchy Level: 1
-- Model version: 9.17
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY conv_core_ip_src_color_correct_core IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Video_in                          :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        ctrl_hStart                       :   IN    std_logic;
        ctrl_hEnd                         :   IN    std_logic;
        ctrl_vStart                       :   IN    std_logic;
        ctrl_vEnd                         :   IN    std_logic;
        ctrl_valid                        :   IN    std_logic;
        Video_out                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        valid_out_hStart                  :   OUT   std_logic;
        valid_out_hEnd                    :   OUT   std_logic;
        valid_out_vStart                  :   OUT   std_logic;
        valid_out_vEnd                    :   OUT   std_logic;
        valid_out_valid                   :   OUT   std_logic
        );
END conv_core_ip_src_color_correct_core;


ARCHITECTURE rtl OF conv_core_ip_src_color_correct_core IS

  -- Component Declarations
  COMPONENT conv_core_ip_src_Subsystem1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          channel_in                      :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
          Enable                          :   IN    std_logic;
          Video_out                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : conv_core_ip_src_Subsystem1
    USE ENTITY work.conv_core_ip_src_Subsystem1(rtl);

  -- Signals
  SIGNAL valid                            : std_logic;
  SIGNAL Subsystem1_out1                  : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Subsystem1 : conv_core_ip_src_Subsystem1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              channel_in => Video_in,  -- uint32
              Enable => valid,
              Video_out => Subsystem1_out1  -- uint32
              );

  valid <= ctrl_valid;

  Video_out <= Subsystem1_out1;

  valid_out_hStart <= ctrl_hStart;

  valid_out_hEnd <= ctrl_hEnd;

  valid_out_vStart <= ctrl_vStart;

  valid_out_vEnd <= ctrl_vEnd;

  valid_out_valid <= ctrl_valid;

END rtl;

